import { Component, OnInit, TemplateRef, viewChild } from '@angular/core';
import Swiper from 'swiper';

@Component({
  selector: 'app-speciality',
  standalone: false,
  templateUrl: './speciality.component.html',
  styleUrl: './speciality.component.scss',
})
export class SpecialityComponent implements OnInit {
  discounts = [
    { key: 1, name: 'Smile Design Veneer Prices' },
    { key: 2, name: 'Removable Veneer Prices' },
    { key: 3, name: 'Permanent Veneer Prices' },
    { key: 4, name: 'Ceramic Veneer Prices' },
    { key: 5, name: 'Best Veneer Prices' },
    { key: 6, name: 'Fixed Veneer Prices' },
    { key: 7, name: 'Front Tooth Veneer Costs' },
  ];
  dentalCosts = [
    { title: 'Dental Implant Cost' },
    { title: 'Tooth Restoration Cost' },
    { title: 'Orthodontic Treatment Cost' },
    { title: 'Root Canal Treatment Cost' },
    { title: 'Scaling and Polishing Cost' },
    { title: 'Dental Veneer Cost' },
    { title: 'Teeth Whitening (Bleaching) Cost' },
    { title: 'Tooth Filling Cost' },
  ];
  bestSelling = [
    {
      imgSergury: '/assets/images/ui/Dental/1.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 1,
      specialty: 'Professional Teeth Whitening',
      promotion: '20% Off',
      description:
        'Achieve a brighter smile with our advanced teeth whitening services.',
      price: 150,
      discountedPrice: 120,
      off: '20%',
      drName: 'Dr. Emily White',
      address: '123 Bright Smile Ave, Dentaltown, TX',
      opinion: 'Highly recommended for a brighter smile!',
      DepositPayment: 2000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/11.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 2,
      specialty: 'Dental Implants',
      promotion: 'Save $500',
      description:
        'Get a permanent solution for missing teeth with our high-quality dental implants.',
      price: 3000,
      discountedPrice: 2500,
      off: '17%',
      drName: 'Dr. John Smith',
      address: '456 Tooth Rebuild Blvd, Implant City, CA',
      opinion: 'An excellent choice for replacing missing teeth.',
      DepositPayment: 5000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/12.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 3,
      specialty: 'Root Canal Treatment',
      promotion: '15% Off',
      description:
        'Relieve pain and restore your tooth with our precise root canal treatment.',
      price: 500,
      discountedPrice: 425,
      off: '15%',
      drName: 'Dr. Sarah Green',
      address: '789 Root Canal Rd, Pain Relief City, FL',
      opinion: 'Efficient and pain-free root canal treatment.',
      DepositPayment: 1500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/13.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 4,
      specialty: 'Orthodontics (Braces)',
      promotion: 'Free Consultation',
      description:
        'Straighten your teeth with our expert orthodontic services.',
      price: 2500,
      discountedPrice: 2500,
      off: '0%',
      drName: 'Dr. Laura Brown',
      address: '321 Aligner Ave, Braces City, NY',
      opinion: 'Perfect for achieving a straighter smile.',
      DepositPayment: 3000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/14.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 5,
      specialty: 'Dental Veneers',
      promotion: 'Buy 4, Get 1 Free',
      description: 'Enhance the appearance of your teeth with natural-looking.',
      price: 1200,
      discountedPrice: 960,
      off: '20%',
      drName: 'Dr. Kevin Blue',
      address: '567 Veneer Valley Rd, Smile Town, IL',
      opinion: 'Amazing results for a perfect smile!',
      DepositPayment: 2500,
    },
    {
      imgSergury: '/assets/images/ui/Dental/1.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 1,
      specialty: 'Professional Teeth Whitening',
      promotion: '20% Off',
      description:
        'Achieve a brighter smile with our advanced teeth whitening services.',
      price: 150,
      discountedPrice: 120,
      off: '20%',
      drName: 'Dr. Emily White',
      address: '123 Bright Smile Ave, Dentaltown, TX',
      opinion: 'Highly recommended for a brighter smile!',
      DepositPayment: 2000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/2.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 2,
      specialty: 'Dental Implants',
      promotion: 'Save $500',
      description:
        'Get a permanent solution for missing teeth with our high-quality dental implants.',
      price: 3000,
      discountedPrice: 2500,
      off: '17%',
      drName: 'Dr. John Smith',
      address: '456 Tooth Rebuild Blvd, Implant City, CA',
      opinion: 'An excellent choice for replacing missing teeth.',
      DepositPayment: 5000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/3.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 3,
      specialty: 'Root Canal Treatment',
      promotion: '15% Off',
      description:
        'Relieve pain and restore your tooth with our precise root canal treatment.',
      price: 500,
      discountedPrice: 425,
      off: '15%',
      drName: 'Dr. Sarah Green',
      address: '789 Root Canal Rd, Pain Relief City, FL',
      opinion: 'Efficient and pain-free root canal treatment.',
      DepositPayment: 1500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/4.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 4,
      specialty: 'Orthodontics (Braces)',
      promotion: 'Free Consultation',
      description:
        'Straighten your teeth with our expert orthodontic services.',
      price: 2500,
      discountedPrice: 2500,
      off: '0%',
      drName: 'Dr. Laura Brown',
      address: '321 Aligner Ave, Braces City, NY',
      opinion: 'Perfect for achieving a straighter smile.',
      DepositPayment: 3000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/5.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 5,
      specialty: 'Dental Veneers',
      promotion: 'Buy 4, Get 1 Free',
      description: 'Enhance the appearance of your teeth with natural-looking.',
      price: 1200,
      discountedPrice: 960,
      off: '20%',
      drName: 'Dr. Kevin Blue',
      address: '567 Veneer Valley Rd, Smile Town, IL',
      opinion: 'Amazing results for a perfect smile!',
      DepositPayment: 2500,
    },
  ];
  dentalDiscount = [
    {
      imgSergury: '/assets/images/ui/Dental/1.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 1,
      specialty: 'Professional Teeth Whitening',
      promotion: '20% Off',
      description:
        'Achieve a brighter smile with our advanced teeth whitening services.',
      price: 150,
      discountedPrice: 120,
      off: '20%',
      drName: 'Dr. Emily White',
      address: '123 Bright Smile Ave, Dentaltown, TX',
      opinion: 'Highly recommended for a brighter smile!',
      DepositPayment: 2000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/2.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 2,
      specialty: 'Dental Implants',
      promotion: 'Save $500',
      description:
        'Get a permanent solution for missing teeth with our high-quality dental implants.',
      price: 3000,
      discountedPrice: 2500,
      off: '17%',
      drName: 'Dr. John Smith',
      address: '456 Tooth Rebuild Blvd, Implant City, CA',
      opinion: 'An excellent choice for replacing missing teeth.',
      DepositPayment: 5000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/3.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 3,
      specialty: 'Root Canal Treatment',
      promotion: '15% Off',
      description:
        'Relieve pain and restore your tooth with our precise root canal treatment.',
      price: 500,
      discountedPrice: 425,
      off: '15%',
      drName: 'Dr. Sarah Green',
      address: '789 Root Canal Rd, Pain Relief City, FL',
      opinion: 'Efficient and pain-free root canal treatment.',
      DepositPayment: 1500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/4.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 4,
      specialty: 'Orthodontics (Braces)',
      promotion: 'Free Consultation',
      description:
        'Straighten your teeth with our expert orthodontic services.',
      price: 2500,
      discountedPrice: 2500,
      off: '0%',
      drName: 'Dr. Laura Brown',
      address: '321 Aligner Ave, Braces City, NY',
      opinion: 'Perfect for achieving a straighter smile.',
      DepositPayment: 3000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/5.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 5,
      specialty: 'Dental Veneers',
      promotion: 'Buy 4, Get 1 Free',
      description: 'Enhance the appearance of your teeth with natural-looking.',
      price: 1200,
      discountedPrice: 960,
      off: '20%',
      drName: 'Dr. Kevin Blue',
      address: '567 Veneer Valley Rd, Smile Town, IL',
      opinion: 'Amazing results for a perfect smile!',
      DepositPayment: 2500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/6.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 6,
      specialty: 'Dentures',
      promotion: '10% Off',
      description: 'Comfortable and durable dentures for a natural smile.',
      price: 800,
      discountedPrice: 720,
      off: '10%',
      drName: 'Dr. Martin King',
      address: '987 Comfort Rd, Denture Land, OH',
      opinion: 'Affordable and high-quality dentures.',
      DepositPayment: 1800,
    },
    {
       imgSergury: '/assets/images/ui/Dental/7.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 7,
      specialty: 'Gum Disease Treatment',
      promotion: 'Free',
      description:
        'Effective treatment for gum disease to restore oral health.',
      price: 300,
      discountedPrice: 300,
      off: '0%',
      drName: 'Dr. Diana Fox',
      address: '654 Healthy Gums Blvd, Smile Town, NJ',
      opinion: 'Great care for maintaining gum health.',
      DepositPayment: 1000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/8.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 8,
      specialty: 'Wisdom Tooth Extraction',
      promotion: 'Save $50',
      description: 'Safe and painless wisdom tooth removal by experts.',
      price: 400,
      discountedPrice: 350,
      off: '12.5%',
      drName: 'Dr. James Grant',
      address: '987 Wisdom Way, Extraction City, CA',
      opinion: 'A stress-free and smooth procedure.',
      DepositPayment: 900,
    },
    {
       imgSergury: '/assets/images/ui/Dental/9.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 9,
      specialty: 'Smile Design',
      promotion: '30% Off',
      description:
        'Transform your smile with our advanced smile design services.',
      price: 5000,
      discountedPrice: 3500,
      off: '30%',
      drName: 'Dr. Julia Lee',
      address: '321 Perfect Smile St, Design City, TX',
      opinion: 'Highly creative and transformative!',
      DepositPayment: 8000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/10.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 10,
      specialty: 'Full Mouth Rehabilitation',
      promotion: 'Custom Quote',
      description: 'Comprehensive solutions for restoring your oral health.',
      price: 10000,
      discountedPrice: 9000,
      off: '10%',
      drName: 'Dr. Walter Green',
      address: '654 Rehab Rd, Oral Health Town, FL',
      opinion: 'Complete care for a beautiful and functional smile.',
      DepositPayment: 15000,
    },
  ];
  latestDental = [
    {
      imgSergury: '/assets/images/ui/Dental/1.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 1,
      specialty: 'Professional Teeth Whitening',
      promotion: '20% Off',
      description:
        'Achieve a brighter smile with our advanced teeth whitening services.',
      price: 150,
      discountedPrice: 120,
      off: '20%',
      drName: 'Dr. Emily White',
      address: '123 Bright Smile Ave, Dentaltown, TX',
      opinion: 'Highly recommended for a brighter smile!',
      DepositPayment: 2000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/2.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 2,
      specialty: 'Dental Implants',
      promotion: 'Save $500',
      description:
        'Get a permanent solution for missing teeth with our high-quality dental implants.',
      price: 3000,
      discountedPrice: 2500,
      off: '17%',
      drName: 'Dr. John Smith',
      address: '456 Tooth Rebuild Blvd, Implant City, CA',
      opinion: 'An excellent choice for replacing missing teeth.',
      DepositPayment: 5000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/3.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 3,
      specialty: 'Root Canal Treatment',
      promotion: '15% Off',
      description:
        'Relieve pain and restore your tooth with our precise root canal treatment.',
      price: 500,
      discountedPrice: 425,
      off: '15%',
      drName: 'Dr. Sarah Green',
      address: '789 Root Canal Rd, Pain Relief City, FL',
      opinion: 'Efficient and pain-free root canal treatment.',
      DepositPayment: 1500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/4.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 4,
      specialty: 'Orthodontics (Braces)',
      promotion: 'Free Consultation',
      description:
        'Straighten your teeth with our expert orthodontic services.',
      price: 2500,
      discountedPrice: 2500,
      off: '0%',
      drName: 'Dr. Laura Brown',
      address: '321 Aligner Ave, Braces City, NY',
      opinion: 'Perfect for achieving a straighter smile.',
      DepositPayment: 3000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/5.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 5,
      specialty: 'Dental Veneers',
      promotion: 'Buy 4, Get 1 Free',
      description: 'Enhance the appearance of your teeth with natural-looking.',
      price: 1200,
      discountedPrice: 960,
      off: '20%',
      drName: 'Dr. Kevin Blue',
      address: '567 Veneer Valley Rd, Smile Town, IL',
      opinion: 'Amazing results for a perfect smile!',
      DepositPayment: 2500,
    },
    {
       imgSergury: '/assets/images/ui/Dental/6.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 6,
      specialty: 'Dentures',
      promotion: '10% Off',
      description: 'Comfortable and durable dentures for a natural smile.',
      price: 800,
      discountedPrice: 720,
      off: '10%',
      drName: 'Dr. Martin King',
      address: '987 Comfort Rd, Denture Land, OH',
      opinion: 'Affordable and high-quality dentures.',
      DepositPayment: 1800,
    },
    {
       imgSergury: '/assets/images/ui/Dental/7.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 7,
      specialty: 'Gum Disease Treatment',
      promotion: 'Free',
      description:
        'Effective treatment for gum disease to restore oral health.',
      price: 300,
      discountedPrice: 300,
      off: '0%',
      drName: 'Dr. Diana Fox',
      address: '654 Healthy Gums Blvd, Smile Town, NJ',
      opinion: 'Great care for maintaining gum health.',
      DepositPayment: 1000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/8.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 8,
      specialty: 'Wisdom Tooth Extraction',
      promotion: 'Save $50',
      description: 'Safe and painless wisdom tooth removal by experts.',
      price: 400,
      discountedPrice: 350,
      off: '12.5%',
      drName: 'Dr. James Grant',
      address: '987 Wisdom Way, Extraction City, CA',
      opinion: 'A stress-free and smooth procedure.',
      DepositPayment: 900,
    },
    {
       imgSergury: '/assets/images/ui/Dental/9.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 9,
      specialty: 'Smile Design',
      promotion: '30% Off',
      description:
        'Transform your smile with our advanced smile design services.',
      price: 5000,
      discountedPrice: 3500,
      off: '30%',
      drName: 'Dr. Julia Lee',
      address: '321 Perfect Smile St, Design City, TX',
      opinion: 'Highly creative and transformative!',
      DepositPayment: 8000,
    },
    {
       imgSergury: '/assets/images/ui/Dental/10.jpg',
      doctorImg: '/./assets/images/ui/doctors/5.jpg',
      key: 10,
      specialty: 'Full Mouth Rehabilitation',
      promotion: 'Custom Quote',
      description: 'Comprehensive solutions for restoring your oral health.',
      price: 10000,
      discountedPrice: 9000,
      off: '10%',
      drName: 'Dr. Walter Green',
      address: '654 Rehab Rd, Oral Health Town, FL',
      opinion: 'Complete care for a beautiful and functional smile.',
      DepositPayment: 15000,
    },
  ];


  readonly templateOne = viewChild.required<TemplateRef<any>>('templateOne');
  readonly templateTwo = viewChild.required<TemplateRef<any>>('templateTwo');
  readonly templateThree = viewChild.required<TemplateRef<any>>('templateThree');
  readonly templatefour = viewChild.required<TemplateRef<any>>('templatefour');

  tabs: {
    id: number;
    title: string;
    template: TemplateRef<any>;
    context?: any;
  }[] = [];

  setDataInTabs() {
    this.tabs = [
      {
        id: 0,
        title: 'Tab 1',
        template: this.templateOne(),
        context: { data: 'Data for Tab 1' },
      },
      {
        id: 1,
        title: 'Tab 2',
        template: this.templateTwo(),
        context: { data: 'Data for Tab 2' },
      },
      {
        id: 3,
        title: 'Tab 3',
        template: this.templateThree(),
        context: { data: 'Data for Tab 3' },
      },
      {
        id: 4,
        title: 'Tab 4',
        template: this.templatefour(),
        context: { data: 'Data for Tab 4' },
      },
    ];
  }
  handleTabChange(index: number) {}

  ngOnInit(): void {
    const serviceSwiper = new Swiper('.serviceSwiper', {
      slidesPerView: 4,
      centeredSlides: true,
      spaceBetween: 30,
      pagination: {
        el: '.swiper-pagination',
        type: 'fraction',
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    
    });
    // var swiper = new Swiper('.discountsSwiper', {
    //   slidesPerView: 5,
    //   spaceBetween: 20,
    //   pagination: {
    //     el: '.swiper-pagination',
    //     clickable: true,
    //     renderBullet: function (index, className) {
    //       return '<span class="' + className + '">' + (index + 1) + '</span>';
    //     },
    //   },
    // });
    // var swiper = new Swiper('latestDentalSwiper', {
    //   slidesPerView: 5,
    //   spaceBetween: 20,
    //   pagination: {
    //     el: '.swiper-pagination',
    //     clickable: true,
    //     renderBullet: function (index, className) {
    //       return '<span class="' + className + '">' + (index + 1) + '</span>';
    //     },
    //   },
    // });
  }
}
