import { Component } from '@angular/core';

@Component({
  selector: 'app-suggestions-ophthalmology-tips',
  standalone: false,
  templateUrl: './suggestions-ophthalmology-tips.component.html',
  styleUrl: './suggestions-ophthalmology-tips.component.scss',
})
export class SuggestionsOphthalmologyTipsComponent {
  ophthalmologyTips = [
    {
      id: 1,
      title: 'Routine Eye Exams',
      description: 'Ensure healthy vision with regular comprehensive eye check-ups.',
      count: 250,
      price: 50,
      discount: 10,
      doctorName: 'Dr. Sophia Nguyen',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Routine Eye Exams.jpg',
      star: 4.8,
      address: '101 Vision Lane, ClearView City',
    },
    {
      id: 2,
      title: 'Cataract Surgery',
      description: 'Restore clarity and improve vision with advanced cataract treatment.',
      count: 150,
      price: 500,
      discount: 15,
      doctorName: 'Dr. Liam Johnson',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Cataract Surgery.jpg',
      star: 4.9,
      address: '202 BrightPath Blvd, Clear Vision Town',
    },
    {
      id: 3,
      title: 'Glaucoma Treatment',
      description: 'Protect your eyes from glaucoma and prevent vision loss.',
      count: 180,
      price: 350,
      discount: 12,
      doctorName: 'Dr. Olivia Davis',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Glaucoma Treatment.png',
      star: 4.7,
      address: '303 SightCare Street, EyeHealth City',
    },
    {
      id: 4,
      title: 'Refractive Surgery',
      description: 'Correct vision issues with advanced refractive surgery techniques.',
      count: 200,
      price: 600,
      discount: 20,
      doctorName: 'Dr. Ethan Brown',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Refractive Surgery.jpg',
      star: 4.8,
      address: '404 VisionFix Avenue, Laser Town',
    },
    {
      id: 5,
      title: 'Dry Eye Treatment',
      description: 'Relieve discomfort and improve eye hydration with expert care.',
      count: 300,
      price: 120,
      discount: 10,
      doctorName: 'Dr. Mia Garcia',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Dry Eye Treatment.jpeg',
      star: 4.6,
      address: '505 Comfort Blvd, TearDrop City',
    },
    {
      id: 6,
      title: 'Diabetic Eye Care',
      description: 'Monitor and manage eye health for patients with diabetes.',
      count: 160,
      price: 300,
      discount: 15,
      doctorName: 'Dr. Benjamin Wilson',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Diabetic Eye Care.jpg',
      star: 4.9,
      address: '606 SugarView Lane, Retina Town',
    },
    {
      id: 7,
      title: 'Contact Lens Fitting',
      description: 'Achieve optimal vision with precise contact lens fitting.',
      count: 220,
      price: 80,
      discount: 5,
      doctorName: 'Dr. Ella Martinez',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Contact Lens Fitting.jpeg',
      star: 4.5,
      address: '707 Lens Lane, Optic Town',
    },
    {
      id: 8,
      title: 'Macular Degeneration Care',
      description: 'Specialized care to manage and treat macular degeneration.',
      count: 140,
      price: 400,
      discount: 10,
      doctorName: 'Dr. Alexander White',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Macular Degeneration Care.jpg',
      star: 4.7,
      address: '808 Retina Road, Vision Care City',
    },
    {
      id: 9,
      title: 'Pediatric Eye Care',
      description: 'Comprehensive eye care services for children.',
      count: 270,
      price: 90,
      discount: 8,
      doctorName: 'Dr. Emily Lopez',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/Pediatric Eye Care.webp',
      star: 4.6,
      address: '909 KidsView Street, EyeSmile Town',
    },
    {
      id: 10,
      title: 'LASIK Surgery',
      description: 'Achieve perfect vision with state-of-the-art LASIK technology.',
      count: 100,
      price: 700,
      discount: 20,
      doctorName: 'Dr. Daniel Moore',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/ophthalmologyTips/LASIK Surgery.jpg',
      star: 4.9,
      address: '1010 Laser Lane, Focus City',
    },
  ];
}
