import { Component } from '@angular/core';

@Component({
  selector: 'app-suggestions-dental',
  standalone: false,
  templateUrl: './suggestions-dental.component.html',
  styleUrl: './suggestions-dental.component.scss',
})
export class SuggestionsDentalComponent {
  dentalServices = [
    {
      id: 1,
      title: 'Dental Implant',
      description: 'Restore missing teeth with permanent and durable implants.',
      count: 500,
      price: 1500,
      discount: 15,
      doctorName: 'Dr. John Doe',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/Dental/Dental Implant.webp',
      star: 4.8,
      address: '123 Smile Avenue, Dental City',
    },
    {
      id: 2,
      title: 'Teeth Whitening',
      description:
        'Brighten your smile with professional whitening treatments.',
      count: 300,
      price: 250,
      discount: 20,
      doctorName: 'Dr. Jane Smith',
      doctorImage: '../../../assets/images/ui/doctors/3.jpg',
      productImage: '../../../assets/images/ui/Dental/Teeth Whitening.jpeg',
      star: 4.7,
      address: '456 Bright Street, White Town',
    },
    {
      id: 3,
      title: 'Dental Veneers',
      description: 'Achieve a flawless smile with custom-made veneers.',
      count: 200,
      price: 1000,
      discount: 10,
      doctorName: 'Dr. Emily Clark',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',

      productImage: '../../../assets/images/ui/Dental/Dental Veneers.webp',
      star: 4.9,
      address: '789 Veneer Road, Perfect Smile City',
    },
    {
      id: 4,
      title: 'Orthodontic Braces',
      description: 'Straighten your teeth and improve your bite.',
      count: 600,
      price: 3000,
      discount: 5,
      doctorName: 'Dr. Alan Wright',
      doctorImage: '../../../assets/images/ui/doctors/4.jpg',
      
      productImage: '../../../assets/images/ui/Dental/Orthodontics.jpg',
      star: 4.6,
      address: '321 Align Avenue, Smile Town',
    },
    {
      id: 5,
      title: 'Root Canal Treatment',
      description: 'Save damaged teeth with effective root canal therapy.',
      count: 400,
      price: 800,
      discount: 10,
      doctorName: 'Dr. Rachel Adams',
      doctorImage: '../../../assets/images/ui/doctors/9.jpg',
      productImage: '../../../assets/images/ui/Dental/Root Canal Therapy.png',
      star: 4.5,
      address: '654 Healthy Tooth Lane, Dental City',
    },
    {
      id: 6,
      title: 'Tooth Extraction',
      description: 'Safe and painless tooth removal services.',
      count: 300,
      price: 150,
      discount: 10,
      doctorName: 'Dr. William Brown',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/Dental/Tooth Extraction.jpg',
      
      star: 4.3,
      address: '987 Care Street, Smile Town',
    },
    {
      id: 7,
      title: 'Dental Cleaning',
      description: 'Thorough cleaning for healthy gums and teeth.',
      count: 800,
      price: 100,
      discount: 5,
      doctorName: 'Dr. Olivia Davis',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/Dental/Dental Cleaning.webp',
      star: 4.7,
      address: '159 Hygiene Blvd, White City',
    },
    {
      id: 8,
      title: 'Gum Disease Treatment',
      description: 'Effective solutions for gum health and protection.',
      count: 500,
      price: 500,
      discount: 15,
      doctorName: 'Dr. Ethan Wilson',
      doctorImage: '../../../assets/images/ui/doctors/5.jpg',
      productImage: '../../../assets/images/ui/Dental/Gum Disease Treatment.jpg',
      
      star: 4.4,
      address: '753 Periodontal Road, Gum Town',
    },
    {
      id: 9,
      title: 'Crowns and Bridges',
      description: 'Restore your smile with crowns and bridges.',
      count: 350,
      price: 1200,
      discount: 10,
      doctorName: 'Dr. Mia Taylor',
      doctorImage: '../../../assets/images/ui/doctors/4.jpg',
      productImage: '../../../assets/images/ui/Dental/Crowns and Bridges.jpg',
      star: 4.6,
      address: '246 Restoration Ave, Dental City',
    },
    {
      id: 10,
      title: 'Pediatric Dentistry',
      description: 'Gentle and specialized dental care for kids.',
      count: 700,
      price: 200,
      discount: 15,
      doctorName: 'Dr. Liam Martinez',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/Dental/Pediatric Dentistry.png',
      star: 4.8,
      address: '135 Kids Smile Blvd, Happy Teeth Town',
    },
  ];
}
