import { Component } from '@angular/core';

@Component({
  selector: 'app-suggestions-skin-hair',
  standalone: false,
  templateUrl: './suggestions-skin-hair.component.html',
  styleUrl: './suggestions-skin-hair.component.scss',
})
export class SuggestionsSkinHairComponent {
  swiperData = [
    {
      id: 1,
      title: 'Mesotherapy',
      description: 'Deep cleansing and nourishing for healthy skin.',
      count: 400,
      price: 120,
      discount: 10,
      doctorName: 'Dr. Sarah Johnson',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      prodcutImage: '../../../assets/images/ui/hair&skin/Mesotherapy.webp',
      star: 4.5,
      address: '123 SkinCare Ave, Beauty City',
    },
    {
      id: 2,
      title: 'Laser Hair Removal',
      description: 'Professional haircuts and custom styling.',
      count: 400,
      price: 300,
      discount: 15,
      doctorName: 'Dr. Michael Lee',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Laser Hair Removal.jpg',
      star: 4.7,
      address: '456 Glow Street, Shine Town',
    },
    {
      id: 3,
      title: 'Filler and Gel Injections',
      description: 'Nail shaping, cuticle care, and polish application.',
      count: 400,
      price: 250,
      discount: 20,
      doctorName: 'Dr. Emily Carter',
      doctorImage: '../../../assets/images/ui/doctors/3.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Filler and Gel Injections.jpg',
      star: 4.8,
      address: '789 Glow Plaza, Wellness Town',
    },
    {
      id: 4,
      title: 'Carboxy Therapy',
      doctorImage: '../../../assets/images/ui/doctors/4.jpg',
      prodcutImage: '../../../assets/images/ui/hair&skin/Carboxy Therapy.jpg',
      count: 400,
      price: 200,
      discount: 5,
      doctorName: 'Dr. Nathan Brooks',
      star: 4.6,
      address: '101 Serenity Blvd, Calm City',
      description:
        'Carboxy therapy improves skin elasticity and reduces cellulite.',
    },
    {
      id: 5,
      title: 'Skin Rejuvenation Laser',
      description: 'Hair removal for smooth skin.',
      count: 400,
      doctorImage: '../../../assets/images/ui/doctors/5.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Skin Rejuvenation Laser.png',
      price: 350,
      discount: 25,
      doctorName: 'Dr. Olivia Smith',
      star: 4.9,
      address: '202 Renewal Road, Glow City',
    },
    {
      id: 6,
      title: 'Eyelid Puffiness Removal',
      description: 'Precision eyebrow and facial hair shaping.',
      count: 400,
      price: 180,
      discount: 10,
      doctorName: 'Dr. Ethan Cooper',
      doctorImage: '../../../assets/images/ui/doctors/7.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Eyelid Puffiness Removal.jpg',
      star: 4.4,
      address: '303 Calm Corner, Peace City',
    },
    {
      id: 7,
      title: 'Facial Skin Rejuvenation',
      description: 'Professional makeup for events and special occasions.',
      count: 400,
      price: 220,
      discount: 15,
      doctorName: 'Dr. Ava Morgan',
      doctorImage: '../../../assets/images/ui/doctors/7.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Facial Skin Rejuvenation.png',
      star: 4.7,
      address: '404 Radiance St, Beauty Town',
    },
    {
      id: 8,
      title: 'Localized Fat Reduction',
      description: 'Relaxation and therapeutic massages.',
      count: 400,
      price: 400,
      doctorImage: '../../../assets/images/ui/doctors/8.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Localized Fat Reduction.jpg',

      discount: 20,
      doctorName: 'Dr. Sophia Wilson',

      star: 4.8,
      address: '505 Wellness Ave, Health City',
    },
    {
      id: 9,
      title: 'Vaginal Rejuvenation',
      description: 'Removing dead skin cells for a refreshed look.',
      count: 400,
      price: 500,
      discount: 30,
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      prodcutImage:
        '../../../assets/images/ui/hair&skin/Vaginal Rejuvenation.jpg',
      doctorName: 'Dr. Grace Miller',
      star: 4.9,
      address: '606 Rejuvenation Road, Fresh City',
    },
    {
      id: 10,
      title: 'Microneedling',
      description: 'Customized treatments for acne-prone skin.',
      count: 400,
      price: 150,
      discount: 12,
      doctorName: 'Dr. Lucas Brown',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      prodcutImage: '../../../assets/images/ui/hair&skin/Microneedling.webp',
      star: 4.5,
      address: '707 SkinCare Lane, Renewal Town',
    },
  ];
}
