import { Component } from '@angular/core';

@Component({
  selector: 'app-suggestions-skin-hair',
  standalone: false,
  templateUrl: './suggestions-skin-hair.component.html',
  styleUrl: './suggestions-skin-hair.component.scss',
})
export class SuggestionsSkinHairComponent {
  swiperData = [
    {
      key: 1,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
    {
      key: 2,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',

      price: 3000,
      off: '20%',
    },
    {
      key: 3,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',

      price: 3000,
      off: '20%',
    },
    {
      key: 4,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
    {
      key: 5,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },

    {
      key: 6,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
    {
      key: 6,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
    {
      key: 6,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
    {
      key: 6,
      name: 'Dentistry',
      title: 'Botox Injection',
      description: 'Full forehead, frown lines, feet using the Masport brand',
      imgSergury: '../../../assets/images/ui/blog/blog.jpg',
      doctorImg: '../../../assets/images/ui/doctors/3.jpg',
      promotion: '20% Off',
      price: 3000,
      off: '20%',
    },
  ];
}
