import { Component } from '@angular/core';

@Component({
  selector: 'app-suggestions-rhinoplasty-tips',
  standalone: false,
  templateUrl: './suggestions-rhinoplasty-tips.component.html',
  styleUrl: './suggestions-rhinoplasty-tips.component.scss',
})
export class SuggestionsRhinoplastyTipsComponent {
   rhinoplastyTips = [
    {
      id: 1,
      title: 'Open Rhinoplasty Procedure',
      description: 'A surgical approach for precise nasal reshaping.',
      count: 150,
      price: 3000,
      discount: 10,
      doctorName: 'Dr. Emma Johnson',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Open Rhinoplasty Procedure.png',
      star: 4.8,
      address: '123 Harmony Street, Shape City',
    },
    {
      id: 2,
      title: 'Closed Rhinoplasty Technique',
      description: 'Minimally invasive rhinoplasty with no visible scars.',
      count: 180,
      price: 2500,
      discount: 8,
      doctorName: 'Dr. Liam Smith',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Closed Rhinoplasty Technique.jpg',
      star: 4.7,
      address: '456 Beauty Avenue, Refine Town',
    },
    {
      id: 3,
      title: 'Revision Rhinoplasty',
      description: 'Corrective surgery to address previous rhinoplasty concerns.',
      count: 100,
      price: 4000,
      discount: 15,
      doctorName: 'Dr. Ava Brown',
      doctorImage: '../../../assets/images/ui/doctors/3.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Revision Rhinoplasty.jpg',
      star: 4.9,
      address: '789 Grace Blvd, Perfection City',
    },
    {
      id: 4,
      title: 'Septoplasty',
      description: 'Surgery to correct deviated septums and improve breathing.',
      count: 200,
      price: 2000,
      discount: 12,
      doctorName: 'Dr. Noah Davis',
      doctorImage: '../../../assets/images/ui/doctors/5.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Septoplasty.jpg',
      star: 4.8,
      address: '101 Airway Lane, Breathing Town',
    },
    {
      id: 5,
      title: 'Non-Surgical Rhinoplasty',
      description: 'Quick, non-invasive nasal contouring with fillers.',
      count: 250,
      price: 800,
      discount: 10,
      doctorName: 'Dr. Mia Wilson',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Non-Surgical Rhinoplasty.jpg',
      star: 4.6,
      address: '202 Glow Street, Refinement City',
    },
    {
      id: 6,
      title: 'Ethnic Rhinoplasty',
      description: 'Tailored nasal reshaping respecting ethnic features.',
      count: 140,
      price: 3500,
      discount: 10,
      doctorName: 'Dr. Ethan Garcia',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Ethnic Rhinoplasty.png',
      star: 4.9,
      address: '303 Diversity Ave, Cultural City',
    },
    {
      id: 7,
      title: 'Nasal Fracture Repair',
      description: 'Comprehensive care to repair nasal fractures.',
      count: 180,
      price: 1500,
      discount: 10,
      doctorName: 'Dr. Sophia Martinez',
      doctorImage: '../../../assets/images/ui/doctors/7.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Nasal Fracture Repair.jpg',
      star: 4.7,
      address: '404 Recovery Lane, Healing City',
    },
    {
      id: 8,
      title: 'Alar Base Reduction',
      description: 'Surgical refinement of wide nostrils.',
      count: 160,
      price: 2200,
      discount: 12,
      doctorName: 'Dr. Lucas White',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Alar Base Reduction.jpg',
      star: 4.8,
      address: '505 Elegance Blvd, Symmetry Town',
    },
    {
      id: 9,
      title: 'Post-Surgery Care',
      description: 'Guidelines and support for optimal recovery post-rhinoplasty.',
      count: 300,
      price: 300,
      discount: 5,
      doctorName: 'Dr. Isabella Taylor',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/Post-Surgery Care.jpg',
      star: 4.7,
      address: '606 Care Street, Wellness City',
    },
    {
      id: 10,
      title: '3D Rhinoplasty Planning',
      description: 'Advanced 3D imaging for personalized surgical planning.',
      count: 120,
      price: 5000,
      discount: 15,
      doctorName: 'Dr. William Johnson',
      doctorImage: '../../../assets/images/ui/doctors/9.jpg',
      productImage: '../../../assets/images/ui/rhinoplasty/3D Rhinoplasty Planning.jpeg',
      star: 4.9,
      address: '707 Innovation Lane, Future Town',
    },
  ];
  
}
