services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch@sha256:fffb0fb3d8305caded6bdfc7c2308133d3a67e71a4011e9867b9a2c3a7a3a7e5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}  # خواندن پسورد از .env
    ports:
      - "9200:9200"
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail ${ELASTICSEARCH_URL}/_cluster/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  kibana:
    image: docker.elastic.co/kibana/kibana@sha256:ffbd605e4891c98d502bd78f474bbe424503cf81496a1bb2a71b58bc8f7742c1
    container_name: kibana
    environment:
        - ELASTICSEARCH_URLS=${ELASTICSEARCH_URL}
        - ELASTICSEARCH_USERNAME=
        - ELASTICSEARCH_PASSWORD=
       
      # - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      # - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      # - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-net

networks:
  elastic-net:
    driver: bridge
