import { Component } from '@angular/core';
import Swiper from 'swiper';

@Component({
  selector: 'app-suggestions-urology-tips',
  standalone: false,
  templateUrl: './suggestions-urology-tips.component.html',
  styleUrl: './suggestions-urology-tips.component.scss',
})
export class SuggestionsUrologyTipsComponent {
   urologyTips = [
    {
      id: 1,
      title: 'Kidney Stone Treatment',
      description: 'Effective treatments for kidney stone removal and pain relief.',
      count: 300,
      price: 400,
      discount: 10,
      doctorName: 'Dr. Liam Carter',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Kidney Stone Treatment.jpg',
      star: 4.8,
      address: '101 StoneCare Lane, Health City',
    },
    {
      id: 2,
      title: 'Bladder Infection Care',
      description: 'Quick and effective care for urinary tract infections.',
      count: 350,
      price: 150,
      discount: 5,
      doctorName: 'Dr. Sophia Harris',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Bladder Infection Care.png',
      star: 4.7,
      address: '202 Comfort Street, Relief Town',
    },
    {
      id: 3,
      title: 'Prostate Health Check',
      description: 'Comprehensive screenings for prostate health.',
      count: 200,
      price: 250,
      discount: 12,
      doctorName: 'Dr. Noah Green',
      doctorImage: '../../../assets/images/ui/doctors/3.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Prostate Health Check.jpg',
      star: 4.9,
      address: '303 Health Avenue, Care City',
    },
    {
      id: 4,
      title: 'Urinary Incontinence Treatment',
      description: 'Specialized care for bladder control issues.',
      count: 180,
      price: 300,
      discount: 10,
      doctorName: 'Dr. Emma Wilson',
      doctorImage: '../../../assets/images/ui/doctors/4.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Urinary Incontinence Treatment.jpg',
      star: 4.6,
      address: '404 Balance Lane, Wellness Town',
    },
    {
      id: 5,
      title: 'Male Fertility Services',
      description: 'Advanced diagnostic and treatment services for male fertility.',
      count: 150,
      price: 500,
      discount: 15,
      doctorName: 'Dr. Lucas Anderson',
      doctorImage: '../../../assets/images/ui/doctors/5.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Male Fertility Services.webp',
      star: 4.9,
      address: '505 Future Street, Parenthood City',
    },
    {
      id: 6,
      title: 'Erectile Dysfunction Treatment',
      description: 'Personalized treatment plans for improved sexual health.',
      count: 220,
      price: 350,
      discount: 10,
      doctorName: 'Dr. Olivia Martinez',
      doctorImage: '../../../assets/images/ui/doctors/7.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Erectile Dysfunction Treatment.jpg',
      star: 4.7,
      address: '606 Care Path, Vitality Town',
    },
    {
      id: 7,
      title: 'Pediatric Urology Care',
      description: 'Expert care for urological issues in children.',
      count: 140,
      price: 200,
      discount: 8,
      doctorName: 'Dr. William Brown',
      doctorImage: '../../../assets/images/ui/doctors/8.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Pediatric Urology Care.jpg',
      star: 4.8,
      address: '707 KidsCare Blvd, Smile City',
    },
    {
      id: 8,
      title: 'Urinary Obstruction Treatment',
      description: 'Advanced care to relieve and manage urinary blockages.',
      count: 170,
      price: 450,
      discount: 12,
      doctorName: 'Dr. Ava White',
      doctorImage: '../../../assets/images/ui/doctors/9.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Urinary Obstruction Treatment.jpg',
      star: 4.9,
      address: '808 Flow Road, Comfort City',
    },
    {
      id: 9,
      title: 'Bladder Cancer Management',
      description: 'Specialized care for early detection and treatment of bladder cancer.',
      count: 120,
      price: 600,
      discount: 15,
      doctorName: 'Dr. Ethan Taylor',
      doctorImage: '../../../assets/images/ui/doctors/2.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Bladder Cancer Management.jpg',
      star: 4.8,
      address: '909 Oncology Lane, Hope Town',
    },
    {
      id: 10,
      title: 'Urinary Tract Health',
      description: 'Comprehensive care for maintaining urinary tract health.',
      count: 400,
      price: 100,
      discount: 10,
      doctorName: 'Dr. Isabella Lee',
      doctorImage: '../../../assets/images/ui/doctors/1.jpg',
      productImage: '../../../assets/images/ui/urologyTips/Urinary Tract Health.avif',
      star: 4.7,
      address: '1010 Wellness Blvd, Happy City',
    },
  ];
  
  
}
